

#!/bin/bash

# get the username and date/time
USERNAME=$(whoami)
DATE_TIME=$(date | awk '{print $1, $2, $3, $4}')

#gather system information
HOSTNAME=$(hostname)
DISTRO=$(lsb_release -d | awk -F'\t' '{print $2}')
UPTIME=$(uptime -p)

#collect hardware details
CPU=$(lshw -class processor | grep "product:" | awk -F': ' '{print $2}' | head -n 1)
RAM=$(awk '/MemTotal/ {printf "%.2f GB\n" ,$2 /1024 /1024}' /proc/meminfo)
DISKS=$(lsblk -d -o NAME,SIZE,MODEL | grep -v "NAME")
VIDEO=$(lspci | grep -i vga | awk -F: '{print $2}' | sed 's/^ //')

#gather network info
/FQDN=$(hostname -f)
IP_ADDRESS=$(ip a | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | cut -d/ -f1)
GATEWAY_IP=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}' )

#gather system status info
USERS=$(who | awk '{print $1}' | sort | uniq | paste -s -d, -)
DISK_SPACE=$(df -h --output=source,avail | grep -v 'Filesystem' | awk '{print $1" "$2}' | tr '\n' ', ')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVG=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ *//')
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | grep -v "State" | cut -d: -f2 | sort | uniq | paste -s -d, -)
UFW_STATUS=$(ufw status | grep -i status | awk '{print $2}')

# output of the collected data in a report
cat <<EOF

System Report generated by $USERNAME, $DATE_TIME

System Information
------------------
Hostname: $HOSTNAME
OS: $DISTRO
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
